#!/bin/sh
/bin/mount -a
sysctl -p

mknod /dev/console c 5 1
mknod /dev/ttyAMA0 c 204 64
mknod /dev/ttyS000 c 204 64
mknod /dev/null	   c 1 3
mkdir /dev/pts
mount -t devpts devpts /dev/pts

PATH=/ipc/bin:/bin:/sbin:/usr/bin:/usr/sbin
LD_LIBRARY_PATH=/ipc/lib:/lib
export PATH LD_LIBRARY_PATH

echo 200000 > /sys/class/net/eth0/queues/tx-0/byte_queue_limits/limit_min
# default ipaddr
if grep -q 'root=/dev/nfs' /proc/cmdline; then
    echo "run on nfs, won't set default ip!"
else
    ETHADDR=`cat /proc/cmdline | xargs -n1 | awk -F'=' '/ethaddr/{print $2}'`
    if [ -n $ETHADDR ]; then
        ifconfig eth0 down;
        ifconfig eth0 hw ether $ETHADDR;
        ifconfig eth0 up
    fi
    ifconfig eth0 192.168.1.217;
    ifconfig lo up;    
fi

# mount without etc/fstab
/sbin/miscmount
mount -t tmpfs tmpfs -o size=50M /tmp
/sbin/mount_as_tmpfs /var/

# syslog
syslogd -s 45 -S -O /tmp/messages
/bin/hostname ty313

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s && echo "mdev is ok......"

echo '
      ^_^                 _____    _           _   _             _
      | |                |  __ \  (_)         (_) | |           | |
      | |   ___    ___   | |  | |  _    __ _   _  | |_    __ _  | |
  _   | |  / __|  / _ \  | |  | | | |  / _` | | | | __|  / _` | | |
 | |__| | | (__  | (_) | | |__| | | | | (_| | | | | |_  | (_| | | |
  \____/   \___|  \___/  |_____/  |_|  \__, | |_|  \__|  \__,_| |_|
                                        __/ |
                                       |___/'

/ipc/etc/auto_run.sh &
